# Generated by Django 4.1.2 on 2022-10-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance_Rule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_function', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.IntegerField()),
                ('apartment_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('id_card_num', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Support_Request',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.acceptance_rule')),
            ],
        ),
        migrations.CreateModel(
            name='Interest_Rate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration_more_than', models.IntegerField()),
                ('duration_less_than_or_equal', models.IntegerField()),
                ('rate', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=40)),
                ('cloud_id', models.CharField(max_length=255)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('rate', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('monthly_total', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('regularity', models.CharField(max_length=255)),
                ('date_signed', models.DateField()),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.clientprofile')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_applied', models.DateField()),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasingapp.clientprofile')),
            ],
        ),
    ]
