# Generated by Django 4.1.2 on 2022-10-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product'),
            preserve_default=False,
        ),
    ]
