# Generated by Django 4.1.2 on 2022-10-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapp', '0002_application_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='monthly_total',
            new_name='regular_payment_size',
        ),
    ]
