# Generated by Django 4.1.2 on 2022-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapp', '0005_alter_acceptance_rule_id_alter_application_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_request',
            name='client_profile',
        ),
        migrations.AddField(
            model_name='support_request',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='support_request',
            name='phone_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
