# Generated by Django 4.1.2 on 2022-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapp', '0006_remove_support_request_client_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cloud_id',
        ),
    ]
