# Generated by Django 4.1.2 on 2022-10-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasingapp', '0012_alter_clientprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leasingapp.clientprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leasingapp.product'),
        ),
    ]
